chapter5Facts = [
    'Conditional statments let us ask questions about the data in our programs.'
    'Conditional statments can only ask questions with a response of either true or false. ',
    'The values true and false are called Booleans.',
    'The part of the conditional statement that asks a question is called a condition or predicate.',
    'A predicate is an expression, such as a comparison or a function, that returns a Boolean value.',
    'An if statement is an example of a conditional.',
    'A block is a group of statements that execute together in a program.',
    'In Python white space is used to define code blocks.',
    'A block of code is offset from its neighbors by being indented with extra spaces.',
    'Once the block is complete the level of indentation goes back a step.',
    'Indentation can use either spaces or tabs.',
    'The number of spaces (or tabs) in each step of indentation is up to the programmer.',
    'Sometimes people argue over code style choices like tabs or spaces, and how many in each indentation step.',
    'It really does\'t matter if you prefer a single tab per indenation step, or two spaces, or four spaces. Just pick something and use it consistently.',
    'Consistent code style helps keep code easy to read.',
    'Many code editors will enforce code style rules, such as 2 spaces per indentation level, automatically.',
    'For if statements, code blocks show what will happen if a condition is found to be true. If the condition is false, the block of code is skipped.',
    'One sort of condition, or predicate, is a comparison like "Is your age greater than nine?"',
    'The book lists several comparision operators, such as not equal to [!=] and greater than [>].',
    'Operators are special characters that perform operations. Comparisons are just one example.',
    'The plus sign [+] is also an operator. But it doesn\'t compare two things. It adds them.',
    'A single equals sign used as an opperator assigns the value on the right side to the variable on the left side.',
    'A double equals sign used as an opperator checks the left and right side for equality.',
    'The double equals vs single equals behavior is the source of lots of mistakes. Even for experienced programmers.',
    'Conditionals can be chained together using elif and else.',
    'Use elif when you want to ask another question.',
    'Use else when you are done asking questions and have something you want to hapen if none of the conditions checked so far were true.',
    'We can build more complex predicates, and ask more complex questions, using logical operators.',
    'Logical operators are keywords such as [and], [or], and [not] that works with Boolean values.',
    'The logical operator [and] combines two Boolean values. The end result will only be true if both sides of the and statement are true.',
    'The logical operator [or] combines two Boolean values. The end result will be true if either side of the or statement is true.',
    'The logical operator [not] flips the value of a single Boolean. True becomes false and false becomes true.',
    'Many programming languages have a specail way of handling a totally empty value. Python uses the keyword [none].',
    'The value [none] is not the same as the string "none" or as the number 0. We know that "none" has four characters. We know that 0 is less than 3. We can\'t know anything about [none] other than that it is [none].',
    'The behavior of [none] is strange. My advice is to avoid it if you can by either not declaring variables until you have a value for them or by declarig variables with a reasonable default value. That\'s not always possible.',
    'Remember from chapter 3 that a string is a collection of characters. And that sometimes those characters can be numbers. But that is still a string. Not a number.',
    'The number [123] is very different from the string ["123"]. Python ALWAYS spots this difference. Programmers can often miss it in our code.',
    'You can convert a string like ["123"] into a number like [123] using the int() function. int("123") returns 123.',
    'You can convert a number like [123] into a string like ["123"] using the str() function. str(123) returns "123".',
    'The int() function assumes you want your integers in base 10. But it takes an optional second parameter that can change the base to stuff like base 16, aka hexidecimal, where A = 10 and F = 16 and 10 = 17. Weird stuff!',
    'Not only are numbers different from strings, but Python has several different numeric types. Intgers are not the same thing as floating point numbers. For now don\'t worry much about the difference beyond that integers are always whole numbers and floats can use a decimal point.',
    'To convert a string like ["3.14"] into a floating point number like [3.14] use the float() function. It works much like the int() funciton.',
    'When Python sees a value that doesn\'t match its expectations it will report the problem usin ValueError.',
]
