chapter3Facts = [
    "Strings give us a way to set apart text to be treated as a value rather than as code",
    "Python needs to know where a string starts and where it ends, so it can start treating text as code again",
    "We mark the beginning and end of a string with quote marks",
    "Strings can be quoted using the single quote character ('), the double quote character(\"), or three single quote characters (''')",
    "The style of quote used at the end of a string MUST match the style of quote used at the start of that string",
    "Syntax is the rules for how words and symbols are used in a language. English has syntax rules. Python has them too.",
    "A SyntaxError means something in the code broke the rules of syntax for Python",
    "Sometimes error messages can contain cryptic jargon like EOL. EOL is an abbreviation for End Of Line."
    "The triple quote style let's us use line breaks inside our strings. That will cause an end of line error with the other two quote styles.",
    "If you want to use the same character inside a string that is used to mark the start and end of that string then you have to escape the character used inside the string with a backslash character (\)",
    '''The triple quote syntax for strings let's us use single quotes (') and double quotes (") in our strings without having to escape them.''',
    "You can think of the terms String substituion, embedding values, and inserting values as interchangable.",
    "In string substitution, placeholders in a string are replaced with whatever values or variables are provided.",
    "Multiple placeholders can be used with string substition provided the values to be substituted are provided in the order they should appear in the template string and wrapped in a pair of parenthesis.",
    "The book doesn't use this term but a list is a basic data structure.",
    "A list stores many values (such as strings) in an ordered way.",
    "We can reference individual values in a list using its index number surrounded by square brackets [].",
    "Lists are numbered starting at zero [0] rather than one [1]. This can be confusing. Even among experienced programmres so called 'off by one errors' are common.",
    "Lists also provide a subset or range syntax. By providing a starting index number ('inclusive' which means it will be included in the subset) and an ending index number ('exclusive' meaning it will NOT be inclued in the subset) with a colon : between them we can get a smaller list (a subset) out of a larger list.",
    "Lists may contain values of all the same types (all strings or all numbers for example) or a mix of several different types of values.",
    "Lists may be nested, which is another way of saying a value in a list may be another list.",
    "Lists expose some functions that provide ways of interacting with them. We call a function 'on' a list using dot notation, which means we put a dot (or period) between the name of the list and the name of the function.",
    "The append() function adds an item to the end of a list.",
    "Values can be removed from a list using the del command. Del is short for 'delete.'",
    
]
